server:
  port: 8080
cupSize: B
age: 18
content: "cupSize:${cupSize},age:${age}"

girl:
  sex: male
  height: 180
  weight: 175
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
